apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-services
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/lemar5555/backstage-learning-gitops.git
        revision: main
        directories:
          - path: environments/*/*/*

  template:
    metadata:
      name: '{{ index .path.segments 1 }}-{{ index .path.segments 2 }}-{{ .path.basename }}'

      labels:
        environment: '{{ index .path.segments 1 }}'
        namespace: '{{ index .path.segments 2 }}'
        service: '{{ .path.basename }}'

    spec:
      project: default

      sources:
        - repoURL: https://github.com/lemar5555/backstage-learning-gitops.git
          targetRevision: main
          path: charts/service
          helm:
            valueFiles:
              - $values/environments/{{ index .path.segments 1 }}/{{ index .path.segments 2 }}/{{ .path.basename }}/values.yaml

        - repoURL: https://github.com/lemar5555/backstage-learning-gitops.git
          targetRevision: main
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 }}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true