nameOverride: backstage-payments-service
image:
  repository: ghcr.io/lemar5555/backstage-payments-service
  tag: "aab5761"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-pull-secret
replicaCount: 1
service:
  type: ClusterIP
  port: 3000
containerPort: 3000
env:
  LOG_LEVEL: info
resources: {}
