nameOverride: ""

replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

env: {}

resources: {}
