apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride | default .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
